server:
  port: 8081
spring:
  application:
    name: email
  profiles:
    active:
      - local

---

spring:
  config:
    activate:
      on-profile:
        - local
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    addresses: ${RABBIT_URL}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USERNAME}
    password: ${PASSWORD_EMAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
broker:
  queue:
    email:
      name: default.email
